const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const UPDATE_CART = "UPDATE_CART";
const EMPTY_CART = "EMPTY_CART";
const GET_ALL_CART_ITEMS = "GET_ALL_CART_ITEMS";

export { ADD_TO_CART, REMOVE_FROM_CART, UPDATE_CART, EMPTY_CART, GET_ALL_CART_ITEMS };