const LOGGED_IN_USER = "LOGGED_IN_USER";
const LOGGED_OUT_USER = "LOGGED_OUT_USER";
const FETCH_USER_INFO = "FETCH_USER_INFO";
const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS";
const FETCH_USER_INFO_FAILURE = "FETCH_USER_INFO_FAILURE";

export {LOGGED_IN_USER, LOGGED_OUT_USER, FETCH_USER_INFO_FAILURE, FETCH_USER_INFO_SUCCESS, FETCH_USER_INFO};
